apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpZeApOekk1TVRSYUZ3MDBNekF4TWpZeE56STVNVFJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERkdlL25ud3FVZ3hrV2d0M0ltdXRlbzJDZE1TbEl2REV6UzNOdE5CdGRnRUlxbHE4TApPZFFhNWhaQUJBVldkdnlub2hMRktCTk1PS2V2bTZSK3hza0NqalJyeU9WZG9rR0ZidDVneHVEVzA5ZERYRTdTCjduQUVoTkwzK2xzZ20wbTNzVHJkNUE4VmZQN0taSlIvSS9JOC9qdlAzTjFPeng1WjRZblhGZGxiUk5NS2xEbFYKbmhxVmE4cTJPMzdFaEhvUndPZ3JncjZxdUdPaGxHQnByZHdVdzBxd3hIVEdRK1F5WnZibm9iOWpieHRSOUVESQpiTTdFdVBRRkRhUFZMU3hWVkZlYzNDU3F5RmRQbVkwSWI5STYraTNZRndvN3l6eU5XUjViS3k3b2dubzVaV2UyCjNqbEdFZDZWbDVVcGFiNW9JeHdBT1dxREsrNzZ5M2Znd0pXZEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlE4WlNWOFoxUkxuSjQ1eDZxRgo5MmtaMURjNUVEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFwZC9LT09VOGExeTNKMU5CMFlMTXQxZ0FxeWx3CmMxbGZMN1hWWkVSU2xOZ3RFaEpwb3c0Rk1yZERKcXUyak1JbUR2U1lyU3pkeWtKS1dTck0wUngrdlhJT2VhK3MKMnhvakdINWQzVVg2dldNRUhIYlZUakc2NTB0dTBRWGhKc3lBb0xJMkFRTWpnalhleXZnNTlNVnFxQ0F2R1YwegpuNWxIR2N5SXI5Vm1ib3hobzcrd1RrUGN6dXFmbm1oMWhPaXRpYlBxSzFzNWJOTGU5cE0vTlNTa1pGNHo5R2lOCkRxaFgyMDdPQURXR3dYY0U2MnVDMlV5VUxpcW0vSmVvd0FtSlNnbzdnd3lUVTk1L0tqZHZXbmJ1RW5YZTNNU2oKWWJ0SU1XU3Iwc0ZaWGVuajduVWNTY3pmMndrWVE2Sm44d0V0NCtQMWJKVTB5M2lIK0N5d2lCQVh6dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://97875676-5597-4746-93a4-d76fa6587992.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_66e633d60e6717dacfbfb8bd3a3b7f8b27f65133f20800bec5d6ed81d2592a7b